# Generated by Django 4.2 on 2023-05-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_employee_address_remove_employee_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
